### ISSUE TITLE
JSON serialization of empty space MOC fails

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/mocpy#146] opened 2024-06-27 13:37 UTC
To reproduce:

```python
from mocpy import MOC
empty = MOC.new_empty(max_depth=0)
empty.serialize("json")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/manon.marchand/Documents/cds-astro-github/mocpy/python/mocpy/serializer.py", line 47, in serialize
    return json.loads(json_str)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/manon.marchand/.conda/envs/mocpy-dev/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manon.marchand/.conda/envs/mocpy-dev/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manon.marchand/.conda/envs/mocpy-dev/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

(causes errors with the MOCServer that loves to return empty MOCs, see issue #143 )

**Comment by fxpineau** [comment] 2024-06-27 13:47
Is the empty MOC completely empty or does it contains at least the order max, e.g. `8/`?
In the second case, it is a bug. In the first case (empty string) it is not a bug but a miss-usage: we need to know at least the depth max to init an empty MOC.

**Comment by fxpineau** [comment] 2024-06-28 13:20
Fixed in MOC Lib Rust, see  [this commit](https://github.com/cds-astro/cds-moc-rust/commit/9477f49c468e4585eb0cb6b6657c35291a652c17), since v0.15. 
Already pushed on [crates.io](https://crates.io/crates/moc) and fixed in MOCPy branch [pyo3v21, see first commit](https://github.com/cds-astro/mocpy/commit/6058346a0aa7cf3d4f1b2ed817f5b0ded5504aad).

**Closed** 2024-07-10 09:23 UTC
Labels: bug
