### ISSUE TITLE
"'NoneType' not callable" from contains_lonlat

### ISSUE THREAD

**Issue by tikk3r** [cds-astro/mocpy#176] opened 2024-09-11 14:49 UTC
Running the following bit of code:

```python
from mocpy import MOC
moc = MOC.from_fits('LockmanHole_ILT_MFS-image-pb_MOC.fits') 
vtab = Table.read('catalogue_VLASS.fits')
coords = SkyCoord(vtab['RAJ2000'], vtab['DEJ2000'], frame='fk5')
vtab = vtab[moc.contains_lonlat(coords.ra, coords.dec)]
```

I see the following error message, although the program does not crash:
```python
Exception ignored in: <function AbstractMOC.__del__ at 0x7fd1421132e0>
Traceback (most recent call last):
  File "/home/ddkq81/.pyenv/lib64/python3.12/site-packages/mocpy/abstract_moc.py", line 26, in __del__
TypeError: 'NoneType' object is not callable
```
Commenting out `mocpy.drop(self.store_index)` in that file makes the message disappear, but I doubt this is the desirable long-term solution :grimacing: I am using mocpy 0.16.2.

**Comment by ManonMarchand** [comment] 2024-09-12 07:36
Hi!

Indeed that's not the ideal solution :laughing: 

I tried reproducing in a similar use case but could not:

```python
from mocpy import MOC
from astroquery.vizier import Vizier
from astropy.coordinates import SkyCoord
moc = MOC.from_string("0/0-11")
vtab = Vizier.get_catalogs("J/ApJS/255/30")[0]
coords = SkyCoord(vtab["RAJ2000"], vtab["DEJ2000"], unit="deg")
vtab[moc.contains_skycoords(coords)]
```

Could you maybe share your files so that we can explore what's happening? (our emails are in the `pyproject.toml` if you don't fell like doing it on github)

Also, are you using multiprocessing or threading? This looks like a garbage collector trying to delete the same MOC twice.

**Comment by tikk3r** [comment] 2024-09-13 11:09
Hmm I indeed do not see it in that example that you present. In fact, now trying to make a minimal example, my original code now no longer shows that error either...

**Comment by ManonMarchand** [comment] 2024-09-13 11:24
If you manage to see it again in a MRE, we're very interested

**Comment by ManonMarchand** [comment] 2024-09-30 14:18
Closing this. Don't hesitate to open a new issue if you're able to reproduce the bug.

**Closed by ManonMarchand** 2024-09-30 14:18 UTC
Labels: need-to-reproduce
